Com 16/develop user login
Startup-Chihuahua/community-api pull request #1
Opened 2022-12-08 17:28 UTC by isaacGon

Added middleware to validate token and a new parameter on swagger to add token on each request

2022-12-14 21:15 UTC, gonzajo requested changes

2022-12-14 21:15 UTC, gonzajo commented on src/database/community-respository.js
> +        return data;
the name of the method should be `findCommunities`

2022-12-14 21:15 UTC, gonzajo commented on src/database/community-respository.js
> +        return data;
the name of the method should be `findOneCommunity`

2022-12-14 21:15 UTC, gonzajo commented on src/database/company-repository.js
> +        return data;
check typos the name of the method should be `findCompanies`

2022-12-14 21:15 UTC, gonzajo commented on src/services/community-service.js
> +            return allCommunitys = await communityData.getComunnitys();
no need to equal to return just return the data from the repository

```javascript
return communityRepository.findCommunities();
```

2022-12-14 21:15 UTC, gonzajo commented on src/services/community-service.js
> +        const community = await communityData.getOneCommunity(communityId);
the repository should handle the non existence of the entity not the service

2022-12-14 21:15 UTC, gonzajo commented on src/services/community-service.js
> +        if(data.affectedRows === 0){
same comment as above the repository should handle the non existence of the entity

2022-12-14 21:15 UTC, gonzajo commented on src/services/company-service.js
> +        return allCompanys = await companyData.getCompanys();
`companyData` should be `companyRepository`

2022-12-14 21:15 UTC, gonzajo commented on src/services/company-service.js
> +        const company = await companyData.getOneCompany(companyId);
same comment for handle the non existence entity

2022-12-14 21:15 UTC, gonzajo commented on src/services/company-service.js
> +        if(data.affectedRows === 0){
same

2022-12-14 21:15 UTC, gonzajo commented on src/services/login-service.js
> +            const userCreden = user[0];
this should be in the repository

or can gime me an example of the response pliss?

2023-01-03 18:39 UTC, gonzajo requested changes

2023-01-03 18:39 UTC, gonzajo commented on src/controllers/community-controller.js
> +        const communiity = await communityService.findOneCommunity(communityId);
```suggestion
        const community = await communityService.findOneCommunity(communityId);
```

2023-01-03 18:39 UTC, gonzajo commented on src/repositories/event-repository.js
> +        if(data.length === 0){
why are you checking with length?

the event is an array?

2023-01-03 18:39 UTC, gonzajo commented on src/repositories/user-repository.js
> +        if(data.length === 0){
same here

2023-01-03 18:39 UTC, gonzajo commented on src/repositories/user-repository.js
> +        if(data.length === 0){
same here

2023-01-03 18:39 UTC, gonzajo commented on src/routes/community-routes.js
> +router.get("/findOneCommunity/:communityId", communityController.findOneCommunity);
this is wrong it should be
- to get all communities `GET /communities`
- to get one community `GET /communities/{communityId}`
- create community `POST /communities` 
- update community `PUT /communities/{communityId}`
- delete community `DELETE /communities/{communityId}`

if you have questions let me know 

also you can follow this article [resource-naming](https://restfulapi.net/resource-naming/)

2023-01-03 18:39 UTC, gonzajo commented on src/routes/company-routes.js
> +router.get("/findOneCompany/:companyId", companyController.findOneCompany);
follow the naming conventions

2023-01-03 18:39 UTC, gonzajo commented on src/routes/event-routes.js
> +router.get("/findOneEvent/:eventId", eventController.findOneEvent);
follow the naming conventions

2023-01-03 18:39 UTC, gonzajo commented on src/routes/user-routes.js
> +router.get("/findOneUser/:userId", userController.findOneUser);
follow the naming conventions

2023-01-03 18:39 UTC, gonzajo commented on src/services/login-service.js
> +        // const validatePass = bcrypt.compareSync(password, userCreden.password);
???

2023-01-05 16:32 UTC, isaacGon commented on src/services/login-service.js
> +        // const validatePass = bcrypt.compareSync(password, userCreden.password);
i'm going to change the way we storage the password, it's going to be encrypted instead of hashed the password

2023-01-23 19:08 UTC, gonzajo approved these changes

2023-01-23 19:08 UTC, gonzajo commented on .vscode/settings.json
> +  // "prettier.trailingComma": "all",
remove this if you are not using it

2023-01-23 19:09 UTC, merged